# Generated by Django 2.2.3 on 2019-08-09 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('body', models.TextField()),
                ('view', models.IntegerField(default=0, verbose_name='بازدیدها')),
                ('show', models.BooleanField(default=1, verbose_name='نمایش')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
