# Generated by Django 2.2.3 on 2019-09-10 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ارسال')),
            ],
        ),
    ]
