# Generated by Django 2.2.3 on 2019-09-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
    ]
