# Generated by Django 2.2.3 on 2019-09-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='created_at',
        ),
    ]
