# Generated by Django 2.2.3 on 2019-09-09 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_remove_contactus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان قرارگیری'),
        ),
    ]
