# Generated by Django 2.2.3 on 2019-09-10 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='mobile',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره وارد شده صحیح نیست', regex='^(09)\\d{9,9}$')]),
        ),
    ]
